SET IDENTITY_INSERT [dbo].[Phones] ON
INSERT INTO [dbo].[Phones] ([PhoneId], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (1, N'HTC Desire 320', N'Экран (4.5", TFT, 854x480)/ MediaTek MT6582M (1.3 ГГц)/ основная камера: 5 Мп, фронтальная камера: 0.3 Мп/ RAM 1 ГБ/ 4 ГБ встроенной памяти + microSD/SDHC (до 32 ГБ)/ 3G/ GPS/ поддержка 2х SIM-карт (Micro-SIM)/ Android 4.2 (Jelly Bean)/ 2000 мА*ч', CAST(2000.00 AS Decimal(18, 2)), N'Smartphone', NULL, NULL)
INSERT INTO [dbo].[Phones] ([PhoneId], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (2, N'Samsung Galaxy J7(new)', N'Экран (5.5", Super AMOLED, 1280x720)/ Восьмиядерный (1.6 ГГц)/ основная камера: 13 Мп, фронтальная камера: 5 Мп/ RAM 2 ГБ/ 16 ГБ встроенной памяти + microSD/SDHC (до 128 ГБ)/ 3G/ GPS/ поддержка 2х SIM-карт (Micro-SIM)/ Android 6.0 (Marshmallow) / 3300 мА*ч', CAST(3500.00 AS Decimal(18, 2)), N'Smartphone', NULL, NULL)
INSERT INTO [dbo].[Phones] ([PhoneId], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (3, N'Huawei P9 Titanium Grey', N'Экран (5.2", IPS, 1920x1080)/ HiSilicon Kirin 955 (4 ядра 2.5 ГГц + 4 ядра 1.8 ГГц)/ Две основные камеры: 12 Мп + 12 Мп, фронтальная камера: 8 Мп/ RAM 3 ГБ/ 32 ГБ встроенной памяти + microSD/SDHC (до 32 ГБ)/ 3G/ GPS/ поддержка 2х SIM-карт (Nano-SIM)/ Android 6.0 (Marshmallow)/ 3000 мА*ч', CAST(1500.00 AS Decimal(18, 2)), N'Smartphone', NULL, NULL)
INSERT INTO [dbo].[Phones] ([PhoneId], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (5, N'Apple iPhone 6s', N'Экран (4.7", IPS, 1334x750)/ Apple A9 (1.8 ГГц)/ основная камера: 12 Мп, фронтальная камера: 5 Мп/ RAM 2 ГБ/ 32 ГБ встроенной памяти/ 3G/ LTE/ GPS/ Nano-SIM/ iOS 9/', CAST(5000.00 AS Decimal(18, 2)), N'Smartphone', NULL, NULL)
INSERT INTO [dbo].[Phones] ([PhoneId], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (6, N'Nokia 230 Dual Sim Dark Silver', N'Экран (2.8", TFT, 240x320)/ основная камера: 2 Мп, фронтальная камера: 2 Мп/ RAM 16 МБ/ microSD/SDHC (до 32 ГБ)/ поддержка 2х SIM-карт (Mini-SIM)/ 1200 мА*ч', CAST(500.00 AS Decimal(18, 2)), N'Button', NULL, NULL)
INSERT INTO [dbo].[Phones] ([PhoneId], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (7, N'Prestigio Muze B1 Duo White', N'Экран (2.8", TN, 320x240)/ основная камера: 0.3 Мп/ RAM 32 МБ/ 32 МБ встроенной памяти + microSD (до 32 ГБ)/ поддержка 2х SIM-карт (Mini-SIM)/ 1000 мА*ч', CAST(600.00 AS Decimal(18, 2)), N'Button', NULL, NULL)
INSERT INTO [dbo].[Phones] ([PhoneId], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (8, N'Panasonic KX-TG2511UAT Titan', N'Тип трубки: Беспроводной ЖК-дисплей: Монохромный, голубая подсветка, Определение номера: АОН + Caller ID, Автоответчик: Нет', CAST(200.00 AS Decimal(18, 2)), N'Office phone', NULL, NULL)
INSERT INTO [dbo].[Phones] ([PhoneId], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (9, N'Texet TX-D7605А Black-Silver', N'Тип трубки: Беспроводной ЖК-дисплей: Цветной (65000 оттенков) Определение номера: Caller ID Автоответчик: Нет', CAST(250.00 AS Decimal(18, 2)), N'Office phone', NULL, NULL)
INSERT INTO [dbo].[Phones] ([PhoneId], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (10, N'Lenovo Vibe K5 Note Pro', N'Экран (5.5", IPS, 1920x1080)/ MediaTek Helio P10 (1.8 ГГц)/ основная камера: 13 Мп, фронтальная камера: 8 Мп/ RAM 3 ГБ/ 32 ГБ встроенной памяти + microSD/SDHC (до 128 ГБ)/ 3G/ LTE/ GPS/ поддержка 2х SIM-карт (Nano-SIM)/ Android 5.1 (Lollipop) / 3500 мА*ч', CAST(1200.00 AS Decimal(18, 2)), N'Smartphone', NULL, NULL)
SET IDENTITY_INSERT [dbo].[Phones] OFF
